[package]
name = "push"
version.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config" }
docker = { path = "../docker" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time = { workspace = true, features = ["formatting", "parsing", "macros", "serde"] }
tokio.workspace = true
tracing.workspace = true
libc = "0.2"
