use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use sentinel_protocol::control::v1::{
    CorrosionInspectResult, CorrosionReconcileRequest, CorrosionReconcileResult,
    FirewallInspectResult, FirewallReconcileRequest, FirewallReconcileResult,
    WireguardInspectResult, WireguardPeer, WireguardPeerState, WireguardReconcileRequest,
    WireguardReconcileResult,
};
use sha2::{Digest, Sha256};

const COOLIFY_NFT_TABLE: &str = "coolify_cluster";
pub(crate) const CORROSION_VERSION: &str = "v1.0.0";

pub(crate) fn validate_interface(value: &str) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 15
        || !value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "_.-".contains(c))
    {
        return Err("The WireGuard interface is invalid.".into());
    }
    Ok(())
}

pub(crate) fn validate_wireguard(request: &WireguardReconcileRequest) -> Result<(), String> {
    validate_interface(&request.interface)?;
    if request.listen_port == 0
        || request.revision == 0
        || !request.address.ends_with("/32")
        || request.peers.len() > 99
    {
        return Err("The WireGuard configuration is invalid.".into());
    }
    for peer in &request.peers {
        if peer.public_key.is_empty()
            || peer.endpoint.is_empty()
            || !peer.allowed_ip.ends_with("/32")
            || peer.persistent_keepalive_seconds > 300
        {
            return Err("A WireGuard peer is invalid.".into());
        }
    }
    Ok(())
}

pub(crate) fn render_wireguard(
    request: &WireguardReconcileRequest,
    private_key: &str,
) -> Result<String, String> {
    validate_wireguard(request)?;
    if private_key.trim().is_empty() || private_key.contains('\n') {
        return Err("The WireGuard private key is invalid.".into());
    }
    let mut peers = request.peers.clone();
    peers.sort_by(|a, b| a.allowed_ip.cmp(&b.allowed_ip));
    let mut output = format!(
        "[Interface]\nAddress = {}\nListenPort = {}\nPrivateKey = {}\n\n",
        request.address,
        request.listen_port,
        private_key.trim()
    );
    for peer in peers {
        output.push_str(&render_peer(&peer));
    }
    Ok(output)
}

fn render_peer(peer: &WireguardPeer) -> String {
    format!(
        "[Peer]\nPublicKey = {}\nEndpoint = {}\nAllowedIPs = {}\nPersistentKeepalive = {}\n\n",
        peer.public_key, peer.endpoint, peer.allowed_ip, peer.persistent_keepalive_seconds
    )
}

pub(crate) fn render_firewall(request: &FirewallReconcileRequest) -> Result<String, String> {
    if request.revision == 0
        || request.wireguard_port == 0
        || request.cluster_cidr.is_empty()
        || validate_interface(&request.wireguard_interface).is_err()
        || request.rules.iter().any(|rule| {
            !matches!(rule.chain.as_str(), "input" | "forward" | "output")
                || rule.expression.contains(';')
                || rule.expression.contains('\n')
        })
    {
        return Err("The firewall configuration is invalid.".into());
    }
    let mut chains = [
        (
            "input",
            format!(
                "ct state established,related accept; udp dport {} accept; iifname \"{}\" ip saddr != {} drop;",
                request.wireguard_port, request.wireguard_interface, request.cluster_cidr
            ),
        ),
        (
            "forward",
            format!(
                "ct state established,related accept; iifname \"{}\" ip saddr {} accept; iifname \"{}\" drop;",
                request.wireguard_interface, request.cluster_cidr, request.wireguard_interface
            ),
        ),
        ("output", String::new()),
    ];
    for rule in &request.rules {
        if let Some((_, expressions)) = chains.iter_mut().find(|chain| chain.0 == rule.chain) {
            expressions.push_str(&format!(" {} ;", rule.expression));
        }
    }
    let mut output = format!("table inet {COOLIFY_NFT_TABLE} {{\n");
    for (chain, expressions) in chains {
        output.push_str(&format!(" chain {chain} {{ type filter hook {chain} priority -5; policy accept; {expressions} }}\n"));
    }
    output.push_str("}\n");
    Ok(output)
}

pub(crate) fn render_corrosion(request: &CorrosionReconcileRequest) -> Result<String, String> {
    if request.version.is_empty()
        || request.cluster_id.is_empty()
        || request.bind_address.is_empty()
        || request.peers.len() > 99
    {
        return Err("The Corrosion configuration is invalid.".into());
    }
    let peers = request
        .peers
        .iter()
        .map(|peer| format!("\"{peer}\""))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "# generated by Coolify; do not edit\n[db]\npath = \"/var/lib/corrosion/corrosion.db\"\nschema_paths = [\"/etc/corrosion/schemas\"]\n[gossip]\naddr = \"{}:8787\"\nbootstrap = [{}]\nplaintext = true\n[api]\naddr = \"{}:8080\"\n[admin]\npath = \"/run/corrosion/admin.sock\"\n",
        request.bind_address, peers, request.bind_address
    ))
}

pub(crate) fn ensure_key(root: &Path, interface: &str) -> Result<String, String> {
    ensure_key_with_binary(root, interface, Path::new("wg"))
}

fn ensure_key_with_binary(
    root: &Path,
    interface: &str,
    wireguard: &Path,
) -> Result<String, String> {
    validate_interface(interface)?;
    let dir = root.join("etc/coolify/network");
    fs::create_dir_all(&dir).map_err(|_| "The key directory could not be created.")?;
    fs::set_permissions(&dir, fs::Permissions::from_mode(0o700))
        .map_err(|_| "The key directory permissions could not be set.")?;
    let path = dir.join(format!("{interface}.key"));
    if !path.exists() {
        let output = Command::new(wireguard)
            .arg("genkey")
            .output()
            .map_err(|_| "WireGuard is unavailable.")?;
        if !output.status.success() {
            return Err("WireGuard could not generate a key.".into());
        }
        atomic_write(&path, &output.stdout, 0o600)?;
    }
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600))
        .map_err(|_| "The key permissions could not be set.")?;
    let private = fs::read(&path).map_err(|_| "The private key could not be read.")?;
    let mut child = Command::new(wireguard)
        .arg("pubkey")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|_| "WireGuard is unavailable.")?;
    child
        .stdin
        .as_mut()
        .ok_or("WireGuard input is unavailable.")?
        .write_all(&private)
        .map_err(|_| "WireGuard key input failed.")?;
    let output = child
        .wait_with_output()
        .map_err(|_| "WireGuard public key generation failed.")?;
    if !output.status.success() {
        return Err("WireGuard public key generation failed.".into());
    }
    String::from_utf8(output.stdout)
        .map(|value| value.trim().to_string())
        .map_err(|_| "WireGuard returned an invalid public key.".into())
}

pub(crate) fn atomic_write(path: &Path, contents: &[u8], mode: u32) -> Result<(), String> {
    let parent = path.parent().ok_or("The target path is invalid.")?;
    fs::create_dir_all(parent).map_err(|_| "The target directory could not be created.")?;
    let mut staged_name = path.as_os_str().to_os_string();
    staged_name.push(".tmp");
    let staged = PathBuf::from(staged_name);
    let mut file = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .mode(mode)
        .open(&staged)
        .map_err(|_| "The staged file could not be created.")?;
    file.write_all(contents)
        .and_then(|_| file.sync_all())
        .map_err(|_| "The staged file could not be written.")?;
    fs::set_permissions(&staged, fs::Permissions::from_mode(mode))
        .map_err(|_| "The staged file permissions could not be set.")?;
    fs::rename(staged, path).map_err(|_| "The staged file could not be activated.".to_string())
}

pub(crate) fn hash(contents: &[u8]) -> String {
    format!("{:x}", Sha256::digest(contents))
}

pub(crate) fn state_path(root: &Path, name: &str) -> PathBuf {
    root.join("var/lib/coolify/network").join(name)
}

pub(crate) fn read_applied_state(root: &Path, interface: &str) -> Option<(u64, String)> {
    let contents = fs::read_to_string(state_path(root, &format!("{interface}.state"))).ok()?;
    let (revision, hash) = contents.trim().split_once(' ')?;
    Some((revision.parse().ok()?, hash.to_string()))
}

pub(crate) fn inspect_wireguard(
    root: &Path,
    interface: &str,
    expected_revision: u64,
    expected_hash: &str,
) -> WireguardInspectResult {
    let applied = read_applied_state(root, interface);
    let observed = if root == Path::new("/") {
        Command::new("wg")
            .args(["show", interface, "dump"])
            .output()
            .ok()
            .filter(|output| output.status.success())
            .and_then(|output| parse_wireguard_dump(interface, &output.stdout).ok())
    } else {
        None
    };
    WireguardInspectResult {
        interface: interface.into(),
        public_key: observed
            .as_ref()
            .map_or_else(String::new, |state| state.public_key.clone()),
        listen_port: observed.as_ref().map_or(0, |state| state.listen_port),
        peers: observed.map_or_else(Vec::new, |state| state.peers),
        applied_revision: applied.as_ref().map_or(0, |state| state.0),
        configuration_hash: applied
            .as_ref()
            .map_or_else(String::new, |state| state.1.clone()),
        drifted: applied
            .as_ref()
            .is_none_or(|state| state.0 != expected_revision || state.1 != expected_hash),
    }
}

fn parse_wireguard_dump(interface: &str, dump: &[u8]) -> Result<WireguardInspectResult, String> {
    let text = std::str::from_utf8(dump).map_err(|_| "WireGuard returned invalid state.")?;
    let mut lines = text.lines();
    let interface_fields = lines
        .next()
        .ok_or("WireGuard returned no interface state.")?
        .split('\t')
        .collect::<Vec<_>>();
    if interface_fields.len() < 4 {
        return Err("WireGuard returned incomplete interface state.".into());
    }
    let public_key = interface_fields[1].to_string();
    let listen_port = interface_fields[2]
        .parse()
        .map_err(|_| "WireGuard returned an invalid listen port.")?;
    let mut peers = Vec::new();
    for line in lines {
        let fields = line.split('\t').collect::<Vec<_>>();
        if fields.len() < 8 {
            return Err("WireGuard returned incomplete peer state.".into());
        }
        peers.push(WireguardPeerState {
            public_key: fields[0].into(),
            endpoint: fields[2].into(),
            allowed_ips: fields[3].split(',').map(str::to_string).collect(),
            latest_handshake_unix_seconds: fields[4].parse().unwrap_or(0),
        });
    }
    Ok(WireguardInspectResult {
        interface: interface.into(),
        public_key,
        listen_port,
        peers,
        applied_revision: 0,
        configuration_hash: String::new(),
        drifted: false,
    })
}

pub(crate) fn reconcile_wireguard(
    root: &Path,
    request: &WireguardReconcileRequest,
) -> Result<WireguardReconcileResult, String> {
    validate_wireguard(request)?;
    let key_path = root
        .join("etc/coolify/network")
        .join(format!("{}.key", request.interface));
    let public_key = if root == Path::new("/") {
        ensure_key(root, &request.interface)?
    } else {
        String::new()
    };
    let private_key = fs::read_to_string(&key_path)
        .map_err(|_| "The WireGuard private key is missing.".to_string())?;
    let config = render_wireguard(request, private_key.trim())?;
    let configuration_hash = hash(config.as_bytes());
    let prior = read_applied_state(root, &request.interface);
    if prior
        .as_ref()
        .is_some_and(|state| state.0 == request.revision && state.1 == configuration_hash)
    {
        return Ok(WireguardReconcileResult {
            state: Some(wireguard_state(
                request,
                public_key,
                configuration_hash,
                false,
            )),
            changed: false,
            rollback_cancelled: true,
        });
    }

    let config_path = root
        .join("etc/wireguard")
        .join(format!("{}.conf", request.interface));
    let last_good_path = state_path(root, &format!("{}.last-good.conf", request.interface));
    let had_current = config_path.exists();
    if had_current {
        let old = fs::read(&config_path)
            .map_err(|_| "The current WireGuard configuration could not be read.")?;
        atomic_write(&last_good_path, &old, 0o600)?;
    }
    let mut staged_name = config_path.as_os_str().to_os_string();
    staged_name.push(".coolify-stage");
    let staged_path = PathBuf::from(staged_name);
    atomic_write(&staged_path, config.as_bytes(), 0o600)?;
    if root == Path::new("/") {
        activate_wireguard(
            request,
            &staged_path,
            &config_path,
            &last_good_path,
            had_current,
        )?;
    } else {
        fs::rename(&staged_path, &config_path)
            .map_err(|_| "The staged WireGuard configuration could not be activated.")?;
    }
    atomic_write(&last_good_path, config.as_bytes(), 0o600)?;
    atomic_write(
        &state_path(root, &format!("{}.state", request.interface)),
        format!("{} {}\n", request.revision, configuration_hash).as_bytes(),
        0o600,
    )?;
    Ok(WireguardReconcileResult {
        state: Some(if root == Path::new("/") {
            inspect_wireguard(
                root,
                &request.interface,
                request.revision,
                &configuration_hash,
            )
        } else {
            wireguard_state(request, public_key, configuration_hash, false)
        }),
        changed: true,
        rollback_cancelled: true,
    })
}

fn wireguard_state(
    request: &WireguardReconcileRequest,
    public_key: String,
    configuration_hash: String,
    drifted: bool,
) -> WireguardInspectResult {
    WireguardInspectResult {
        interface: request.interface.clone(),
        public_key,
        listen_port: request.listen_port,
        peers: Vec::new(),
        applied_revision: request.revision,
        configuration_hash,
        drifted,
    }
}

fn activate_wireguard(
    request: &WireguardReconcileRequest,
    staged_path: &Path,
    config_path: &Path,
    last_good_path: &Path,
    had_current: bool,
) -> Result<(), String> {
    run(
        Command::new("wg-quick").arg("strip").arg(staged_path),
        "WireGuard validation failed.",
    )?;
    let rollback_unit = format!("coolify-network-rollback-{}", request.interface);
    let rollback_command = if had_current {
        format!(
            "cp '{}' '{}' && (wg-quick down '{}' >/dev/null 2>&1 || true) && wg-quick up '{}'",
            last_good_path.display(),
            config_path.display(),
            request.interface,
            request.interface
        )
    } else {
        format!(
            "wg-quick down '{}' >/dev/null 2>&1 || true; rm -f '{}'",
            request.interface,
            config_path.display()
        )
    };
    run(
        Command::new("systemd-run").args([
            "--unit",
            &rollback_unit,
            "--on-active=60s",
            "/bin/sh",
            "-c",
            &rollback_command,
        ]),
        "The WireGuard rollback could not be armed.",
    )?;
    fs::rename(staged_path, config_path)
        .map_err(|_| "The staged WireGuard configuration could not be activated.")?;
    let _ = Command::new("wg-quick")
        .args(["down", &request.interface])
        .status();
    let healthy = run(
        Command::new("wg-quick").args(["up", &request.interface]),
        "WireGuard activation failed.",
    )
    .and_then(|_| {
        run(
            Command::new("wg").args(["show", &request.interface]),
            "WireGuard health validation failed.",
        )
    })
    .and_then(|_| {
        if request.flux_probe_host.is_empty() {
            Ok(())
        } else {
            run(
                Command::new("ping").args(["-c", "1", "-W", "5", &request.flux_probe_host]),
                "Flux connectivity validation failed.",
            )
        }
    });
    if healthy.is_err() {
        let _ = Command::new("systemctl")
            .args(["start", &rollback_unit])
            .status();
        return Err("WireGuard activation failed and rollback was requested.".into());
    }
    run(
        Command::new("systemctl").args(["stop", &format!("{rollback_unit}.timer")]),
        "The WireGuard rollback could not be cancelled.",
    )
}

pub(crate) fn reconcile_firewall(
    root: &Path,
    request: &FirewallReconcileRequest,
) -> Result<FirewallReconcileResult, String> {
    let snapshot = render_firewall(request)?;
    let configuration_hash = hash(snapshot.as_bytes());
    let state_file = state_path(root, "firewall.state");
    let prior = read_state_file(&state_file);
    if prior
        .as_ref()
        .is_some_and(|state| state.0 == request.revision && state.1 == configuration_hash)
    {
        return Ok(FirewallReconcileResult {
            state: Some(firewall_state(request.revision, configuration_hash, false)),
            changed: false,
            rollback_cancelled: true,
        });
    }
    let snapshot_path = state_path(root, "firewall.nft");
    atomic_write(&snapshot_path, snapshot.as_bytes(), 0o600)?;
    if root == Path::new("/") {
        activate_firewall(root, &snapshot)?;
    }
    atomic_write(
        &state_file,
        format!("{} {}\n", request.revision, configuration_hash).as_bytes(),
        0o600,
    )?;
    Ok(FirewallReconcileResult {
        state: Some(firewall_state(request.revision, configuration_hash, false)),
        changed: true,
        rollback_cancelled: true,
    })
}

fn nft_transaction(snapshot: &str, table_exists: bool) -> String {
    format!(
        "{}{}",
        if table_exists {
            format!("delete table inet {COOLIFY_NFT_TABLE}\n")
        } else {
            String::new()
        },
        snapshot
    )
}

fn activate_firewall(root: &Path, snapshot: &str) -> Result<(), String> {
    let current = Command::new("nft")
        .args(["list", "table", "inet", COOLIFY_NFT_TABLE])
        .output()
        .map_err(|_| "nftables is unavailable.")?;
    let table_exists = current.status.success();
    let last_good = state_path(root, "firewall.last-good.nft");
    if table_exists {
        atomic_write(&last_good, &current.stdout, 0o600)?;
    }
    let transaction_path = state_path(root, "firewall.transaction.nft");
    atomic_write(
        &transaction_path,
        nft_transaction(snapshot, table_exists).as_bytes(),
        0o600,
    )?;
    run(
        Command::new("nft")
            .args(["--check", "--file"])
            .arg(&transaction_path),
        "The firewall configuration is invalid.",
    )?;
    let rollback = if table_exists {
        format!(
            "nft delete table inet {COOLIFY_NFT_TABLE} >/dev/null 2>&1 || true; nft --file '{}'",
            last_good.display()
        )
    } else {
        format!("nft delete table inet {COOLIFY_NFT_TABLE} >/dev/null 2>&1 || true")
    };
    run(
        Command::new("systemd-run").args([
            "--unit",
            "coolify-firewall-rollback",
            "--on-active=60s",
            "/bin/sh",
            "-c",
            &rollback,
        ]),
        "The firewall rollback could not be armed.",
    )?;
    let activated = run(
        Command::new("nft").arg("--file").arg(&transaction_path),
        "The firewall configuration could not be activated.",
    )
    .and_then(|_| {
        run(
            Command::new("nft").args(["list", "table", "inet", COOLIFY_NFT_TABLE]),
            "The Coolify firewall table is not active.",
        )
    });
    if let Err(error) = activated {
        let _ = Command::new("systemctl")
            .args(["start", "coolify-firewall-rollback.service"])
            .status();
        return Err(error);
    }
    run(
        Command::new("systemctl").args(["stop", "coolify-firewall-rollback.timer"]),
        "The firewall rollback could not be cancelled.",
    )?;
    atomic_write(&last_good, snapshot.as_bytes(), 0o600)
}

pub(crate) fn inspect_firewall(
    root: &Path,
    expected_revision: u64,
    expected_hash: &str,
) -> FirewallInspectResult {
    let state = read_state_file(&state_path(root, "firewall.state"));
    FirewallInspectResult {
        applied_revision: state.as_ref().map_or(0, |state| state.0),
        configuration_hash: state
            .as_ref()
            .map_or_else(String::new, |state| state.1.clone()),
        drifted: state
            .as_ref()
            .is_none_or(|state| state.0 != expected_revision || state.1 != expected_hash),
        table: COOLIFY_NFT_TABLE.into(),
    }
}

fn firewall_state(
    revision: u64,
    configuration_hash: String,
    drifted: bool,
) -> FirewallInspectResult {
    FirewallInspectResult {
        applied_revision: revision,
        configuration_hash,
        drifted,
        table: COOLIFY_NFT_TABLE.into(),
    }
}

pub(crate) fn reconcile_corrosion(
    root: &Path,
    request: &CorrosionReconcileRequest,
) -> Result<CorrosionReconcileResult, String> {
    if request.version != CORROSION_VERSION {
        return Err(format!(
            "Corrosion must use the tested version {CORROSION_VERSION}."
        ));
    }
    let config = render_corrosion(request)?;
    let config_path = root.join("etc/corrosion/config.toml");
    let changed = fs::read(&config_path).ok().as_deref() != Some(config.as_bytes());
    atomic_write(&config_path, config.as_bytes(), 0o644)?;
    atomic_write(
        &root.join("etc/corrosion/schemas/coolify.sql"),
        corrosion_schema().as_bytes(),
        0o644,
    )?;
    atomic_write(
        &root.join("etc/systemd/system/corrosion.service"),
        corrosion_unit().as_bytes(),
        0o644,
    )?;
    if root == Path::new("/") {
        install_corrosion(request.version.as_str())?;
        run(
            Command::new("systemctl").arg("daemon-reload"),
            "Systemd could not reload Corrosion.",
        )?;
        run(
            Command::new("systemctl").args(["enable", "--now", "corrosion.service"]),
            "Corrosion could not start.",
        )?;
    }
    Ok(CorrosionReconcileResult {
        state: Some(inspect_corrosion(root)),
        changed,
    })
}

pub(crate) fn inspect_corrosion(root: &Path) -> CorrosionInspectResult {
    let configured = root.join("etc/corrosion/config.toml").exists();
    CorrosionInspectResult {
        version: if configured {
            CORROSION_VERSION.into()
        } else {
            String::new()
        },
        member_state: if configured {
            "configured".into()
        } else {
            "absent".into()
        },
        endpoint_count: 0,
        last_convergence_unix_seconds: None,
    }
}

fn corrosion_schema() -> &'static str {
    "CREATE TABLE IF NOT EXISTS workload_endpoints (workload_id TEXT NOT NULL, namespace TEXT NOT NULL, owner_node_ip TEXT NOT NULL, container_ip TEXT NOT NULL, state TEXT NOT NULL, health TEXT NOT NULL, updated_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY (namespace, workload_id, owner_node_ip, container_ip));\n"
}

fn corrosion_unit() -> &'static str {
    "[Unit]\nDescription=Coolify Corrosion discovery\nAfter=network-online.target wg-quick@coolify0.service\nWants=network-online.target\nRequires=wg-quick@coolify0.service\n[Service]\nExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml\nUser=corrosion\nGroup=corrosion\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=true\nStateDirectory=corrosion\nRuntimeDirectory=corrosion\nReadWritePaths=/var/lib/corrosion /run/corrosion\nRestart=on-failure\nRestartSec=2s\n[Install]\nWantedBy=multi-user.target\n"
}

fn corrosion_download(version: &str, architecture: &str) -> Result<String, String> {
    let target = match architecture.trim() {
        "x86_64" => "x86_64-unknown-linux-gnu",
        "aarch64" => "aarch64-unknown-linux-gnu",
        _ => return Err("The host architecture is not supported by Corrosion.".into()),
    };
    Ok(format!(
        "https://github.com/superfly/corrosion/releases/download/{version}/corrosion-{target}.tar.gz"
    ))
}

fn install_corrosion(version: &str) -> Result<(), String> {
    if fs::read_to_string("/usr/local/bin/corrosion.version")
        .ok()
        .is_some_and(|installed| installed.trim() == version)
        && Path::new("/usr/local/bin/corrosion").exists()
    {
        return Ok(());
    }
    let architecture = Command::new("uname")
        .arg("-m")
        .output()
        .map_err(|_| "The host architecture could not be detected.")?;
    let url = corrosion_download(version, &String::from_utf8_lossy(&architecture.stdout))?;
    let directory = PathBuf::from(format!(
        "/var/lib/coolify/downloads/corrosion-{}",
        std::process::id()
    ));
    fs::create_dir_all(&directory)
        .map_err(|_| "The Corrosion download directory could not be created.")?;
    let archive = directory.join("corrosion.tar.gz");
    run(
        Command::new("curl")
            .args(["-fsSL", "--retry", "3", "--max-time", "120", "-o"])
            .arg(&archive)
            .arg(&url),
        "Corrosion could not be downloaded.",
    )?;
    run(
        Command::new("tar")
            .arg("-xzf")
            .arg(&archive)
            .arg("-C")
            .arg(&directory),
        "Corrosion could not be extracted.",
    )?;
    run(
        Command::new("install")
            .args(["-m", "0755"])
            .arg(directory.join("corrosion"))
            .arg("/usr/local/bin/corrosion"),
        "Corrosion could not be installed.",
    )?;
    atomic_write(
        Path::new("/usr/local/bin/corrosion.version"),
        format!("{version}\n").as_bytes(),
        0o644,
    )?;
    if !Command::new("id")
        .args(["-u", "corrosion"])
        .status()
        .is_ok_and(|status| status.success())
    {
        run(
            Command::new("useradd").args([
                "--system",
                "--home",
                "/var/lib/corrosion",
                "--shell",
                "/usr/sbin/nologin",
                "corrosion",
            ]),
            "The Corrosion service user could not be created.",
        )?;
    }
    let _ = fs::remove_dir_all(directory);
    Ok(())
}

fn run(command: &mut Command, fallback: &str) -> Result<(), String> {
    let output = command.output().map_err(|_| fallback.to_string())?;
    if output.status.success() {
        return Ok(());
    }
    let message = String::from_utf8_lossy(&output.stderr)
        .trim()
        .chars()
        .take(2_000)
        .collect::<String>();
    Err(if message.is_empty() {
        fallback.into()
    } else {
        message
    })
}

fn read_state_file(path: &Path) -> Option<(u64, String)> {
    let contents = fs::read_to_string(path).ok()?;
    let (revision, hash) = contents.trim().split_once(' ')?;
    Some((revision.parse().ok()?, hash.into()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use sentinel_protocol::control::v1::{FirewallRule, WireguardPeer};

    #[test]
    fn renders_deterministic_full_mesh_without_peer_secrets() {
        let request = WireguardReconcileRequest {
            interface: "coolify0".into(),
            address: "10.240.0.2/32".into(),
            listen_port: 51820,
            revision: 1,
            peers: vec![WireguardPeer {
                public_key: "b".into(),
                endpoint: "192.0.2.2:51820".into(),
                allowed_ip: "10.240.0.3/32".into(),
                persistent_keepalive_seconds: 25,
            }],
            flux_probe_host: "10.240.0.1".into(),
        };
        let rendered = render_wireguard(&request, "private").unwrap();
        assert!(rendered.contains("Address = 10.240.0.2/32"));
        assert!(rendered.contains("AllowedIPs = 10.240.0.3/32"));
        assert!(!rendered.contains("PrivateKey = b"));
    }

    #[test]
    fn firewall_output_is_scoped_to_the_coolify_table() {
        let rendered = render_firewall(&FirewallReconcileRequest {
            revision: 1,
            wireguard_port: 51820,
            cluster_cidr: "10.240.0.0/24".into(),
            rules: vec![FirewallRule {
                chain: "forward".into(),
                expression: "ip saddr 10.240.0.0/24 accept".into(),
            }],
            wireguard_interface: "coolify0".into(),
        })
        .unwrap();
        assert!(rendered.contains("table inet coolify_cluster"));
        assert!(!rendered.contains("flush ruleset"));
        assert!(!rendered.contains("delete table"));
    }

    #[test]
    fn atomic_writes_keep_mode_and_replace_content() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("config");
        atomic_write(&path, b"first", 0o600).unwrap();
        atomic_write(&path, b"second", 0o600).unwrap();
        assert_eq!(fs::read(&path).unwrap(), b"second");
        assert_eq!(
            fs::metadata(path).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    #[test]
    fn generates_a_private_key_with_strict_permissions_and_returns_only_the_public_key() {
        let temp = tempfile::tempdir().unwrap();
        let wireguard = temp.path().join("wg");
        fs::write(&wireguard, "#!/bin/sh\nif [ \"$1\" = genkey ]; then echo private-secret; else cat >/dev/null; echo public-only; fi\n").unwrap();
        fs::set_permissions(&wireguard, fs::Permissions::from_mode(0o700)).unwrap();
        let public = ensure_key_with_binary(temp.path(), "coolify0", &wireguard).unwrap();
        let key = temp.path().join("etc/coolify/network/coolify0.key");
        assert_eq!(public, "public-only");
        assert_eq!(fs::read_to_string(&key).unwrap().trim(), "private-secret");
        assert_eq!(
            fs::metadata(key).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    #[test]
    fn wireguard_reconciliation_is_atomic_and_idempotent() {
        let temp = tempfile::tempdir().unwrap();
        let key = temp.path().join("etc/coolify/network/coolify0.key");
        atomic_write(&key, b"private-secret", 0o600).unwrap();
        let request = WireguardReconcileRequest {
            interface: "coolify0".into(),
            address: "10.240.0.2/32".into(),
            listen_port: 51820,
            revision: 7,
            peers: vec![WireguardPeer {
                public_key: "peer-public".into(),
                endpoint: "192.0.2.2:51820".into(),
                allowed_ip: "10.240.0.3/32".into(),
                persistent_keepalive_seconds: 25,
            }],
            flux_probe_host: String::new(),
        };
        let first = reconcile_wireguard(temp.path(), &request).unwrap();
        let second = reconcile_wireguard(temp.path(), &request).unwrap();
        assert!(first.changed);
        assert!(!second.changed);
        assert!(first.rollback_cancelled && second.rollback_cancelled);
        assert_eq!(
            fs::metadata(temp.path().join("etc/wireguard/coolify0.conf"))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        assert!(!format!("{first:?}").contains("private-secret"));
    }

    #[test]
    fn firewall_reconciliation_never_changes_unrelated_rules() {
        let temp = tempfile::tempdir().unwrap();
        let unrelated = temp.path().join("etc/nftables.conf");
        fs::create_dir_all(unrelated.parent().unwrap()).unwrap();
        fs::write(&unrelated, "table inet user_owned {}\n").unwrap();
        let request = FirewallReconcileRequest {
            revision: 3,
            wireguard_port: 51820,
            cluster_cidr: "10.240.0.0/24".into(),
            rules: vec![],
            wireguard_interface: "coolify0".into(),
        };
        let first = reconcile_firewall(temp.path(), &request).unwrap();
        let second = reconcile_firewall(temp.path(), &request).unwrap();
        assert!(first.changed);
        assert!(!second.changed);
        assert_eq!(
            fs::read_to_string(unrelated).unwrap(),
            "table inet user_owned {}\n"
        );
        assert!(
            !fs::read_to_string(state_path(temp.path(), "firewall.nft"))
                .unwrap()
                .contains("flush ruleset")
        );
        let transaction = nft_transaction(&render_firewall(&request).unwrap(), true);
        assert!(transaction.starts_with("delete table inet coolify_cluster"));
        assert!(!transaction.contains("flush ruleset"));
        assert!(!transaction.contains("user_owned"));
    }

    #[test]
    fn corrosion_configuration_is_pinned_bound_and_hardened() {
        let temp = tempfile::tempdir().unwrap();
        let request = CorrosionReconcileRequest {
            version: CORROSION_VERSION.into(),
            cluster_id: "cluster-one".into(),
            bind_address: "10.240.0.2".into(),
            peers: vec!["10.240.0.3:8787".into()],
        };
        let result = reconcile_corrosion(temp.path(), &request).unwrap();
        assert!(result.changed);
        let config = fs::read_to_string(temp.path().join("etc/corrosion/config.toml")).unwrap();
        let unit =
            fs::read_to_string(temp.path().join("etc/systemd/system/corrosion.service")).unwrap();
        let schema =
            fs::read_to_string(temp.path().join("etc/corrosion/schemas/coolify.sql")).unwrap();
        assert!(config.contains("10.240.0.2:8787") && config.contains("10.240.0.2:8080"));
        assert!(unit.contains("NoNewPrivileges=true") && unit.contains("ProtectSystem=strict"));
        assert!(schema.contains("owner_node_ip") && schema.contains("expires_at"));
    }

    #[test]
    fn corrosion_download_is_pinned_to_the_tested_release_and_architecture() {
        assert_eq!(
            corrosion_download(CORROSION_VERSION, "x86_64").unwrap(),
            "https://github.com/superfly/corrosion/releases/download/v1.0.0/corrosion-x86_64-unknown-linux-gnu.tar.gz"
        );
        assert!(corrosion_download(CORROSION_VERSION, "unknown").is_err());
    }

    #[test]
    fn observed_wireguard_state_discards_the_private_and_preshared_keys() {
        let state = parse_wireguard_dump("coolify0", b"private-secret\tpublic-local\t51820\toff\npeer-public\tpreshared-secret\t192.0.2.2:51820\t10.240.0.3/32\t1234\t5\t7\t25\n").unwrap();
        assert_eq!(state.public_key, "public-local");
        assert_eq!(state.peers[0].latest_handshake_unix_seconds, 1234);
        let visible = format!("{state:?}");
        assert!(!visible.contains("private-secret"));
        assert!(!visible.contains("preshared-secret"));
    }
}
