[package]
name = "control"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config = { path = "../config" }
protocol = { path = "../protocol" }
futures-util.workspace = true
prost.workspace = true
reqwest.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2"
serde.workspace = true
serde_json.workspace = true
time.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1"
tonic.workspace = true
tracing.workspace = true
url.workspace = true
x509-parser = "0.18.1"
sysinfo.workspace = true

[dev-dependencies]
axum.workspace = true
rcgen = "0.14.10"
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["net"] }
tonic-health = "0.14.6"
